<?xml version="1.0"?>

<robot name="iris" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg namespace)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://rotors_description/meshes/iris.dae" />
  <xacro:property name="mass" value="1.5" /> <!-- [kg] -->
  <xacro:property name="body_width" value="0.47" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.11" /> <!-- [m] -->
  <xacro:property name="mass_rotor" value="0.005" /> <!-- [kg] -->
  <xacro:property name="arm_length_front_x" value="0.13" /> <!-- [m] -->
  <xacro:property name="arm_length_back_x" value="0.13" /> <!-- [m] -->
  <xacro:property name="arm_length_front_y" value="0.22" /> <!-- [m] -->
  <xacro:property name="arm_length_back_y" value="0.2" /> <!-- [m] -->
  <xacro:property name="rotor_offset_top" value="0.023" /> <!-- [m] -->
  <xacro:property name="radius_rotor" value="0.1" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="12.44460e-06" /> <!-- [kg.m/s^2] --> 
  <!-- for default = 8.54858e-06  --> <!-- for 0.3 kg = 10.44460e-06  -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_rot_velocity" value="1200" /> <!-- [rad/s] -->
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />
  <xacro:property name="sqrt2" value="1.4142135623730951" />
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- Property Blocks -->
  <xacro:property name="body_inertia">
    <inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929" iyz="0.0" izz="0.0977" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property> 

<!--      MODIFIED INERTIA  FOR m = 0.3       -->
  <!-- <xacro:property name="body_inertia">
    <inertia ixx="0.0397563" ixy="0.0" ixz="0.0" iyy="0.0508929" iyz="0.0" izz="0.1077" />
   </xacro:property> -->

  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" />

  <!-- Instantiate multirotor_base_macro once -->
  <xacro:multirotor_base_macro
    robot_namespace="${namespace}"
    mass="${mass}"
    body_width="${body_width}"
    body_height="${body_height}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}"
    >
    <xacro:insert_block name="body_inertia" />
  </xacro:multirotor_base_macro>

  <!-- Instantiate rotors -->
  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="front_right"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length_front_x} -${arm_length_front_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor
    robot_namespace="${namespace}"
    suffix="back_left"
    direction="ccw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="1"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${arm_length_back_x} ${arm_length_back_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="front_left"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="2"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length_front_x} ${arm_length_front_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

  <xacro:vertical_rotor robot_namespace="${namespace}"
    suffix="back_right"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_rot_velocity="${max_rot_velocity}"
    motor_number="3"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${arm_length_back_x} -${arm_length_back_y} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:vertical_rotor>

<!-- Mount a VI-sensor in the front of Neo. 
  <xacro:vi_sensor_macro
      namespace="${namespace}/vi_sensor"
      parent_link="${namespace}/base_link"
      enable_cameras="true"
      enable_depth="true"
      enable_ground_truth="true">
    <origin xyz="0.133 0.0 -0.0565" rpy="0.0 ${20.0/180.0*pi} 0.0" />
  </xacro:vi_sensor_macro>
 
  <xacro:vi_sensor_camera_macro
      namespace="${namespace}/vi_sensor"
      parent_link="${namespace}/base_link"
      camera_suffix="2"
      frame_rate="20">
    <origin xyz="0.019 0.0 0.073" rpy="0.0 ${-pi/2} 0.0" />
  </xacro:vi_sensor_camera_macro>
  
  <xacro:vi_sensor_camera_macro
      namespace="${namespace}/vi_sensor"
      parent_link="${namespace}/base_link"
      camera_suffix="3"
      frame_rate="20">
    <origin xyz="0.019 0.0 -0.045" rpy="0.0 ${pi/2} 0.0" />
  </xacro:vi_sensor_camera_macro>     -->

<!--
  <gazebo reference="sensor">
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.8</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/laser/scan</topicName>
        <frameName>world</frameName>
      </plugin>
    </sensor>
</gazebo> -->

<!-- <link name="laser">
    <inertial>
      <xacro:hokuyo_inertial_params />
    </inertial> 
    <origin xyz="0 0 0" rpy="0 0 0" />
  <mass value="0.100" />
  <inertia ixx="4E-06" ixy="0"           ixz="0"
                            iyy="4E-06"  iyz="0"
                                         izz="4E-06" />
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size = "0.1 0.1 0.1"/>
      </geometry>
    </visual> 
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="2 0 2" rpy="0 0 0"/>
    <parent link="${namespace}/base_link" />
    <child link="laser" />
    <axis xyz="0 0 1" />
</joint>
-->

<!--
<xacro:macro name="hokuyo_laser" params="xyz rpy parent">
    <joint name="hokuyo_laser_joint" type="fixed">
        <axis xyz="0 0 1" />
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <parent link="${namespace}/base_link"/>
        <child link="hokuyo_laser_link"/>
    </joint>
     
    <link name="hokuyo_laser_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.04" radius="0.045"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.04" radius="0.045"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
    
    <gazebo reference="hokuyo_laser_link">
        <gravity>true</gravity>
        <sensor type="ray" name="head_hokuyo_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>40</max>
                    <resolution>0.025</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.0</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <robotNamespace></robotNamespace>
                <topicName>laser_scan</topicName>
                <frameName>hokuyo_laser_link</frameName>
            </plugin>      
        </sensor>
    </gazebo>
 
</xacro:macro> -->


<!-- <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro"/>
<hokuyo_utm30lx_model name="hokuyo_laser" parent="base_link">
  <origin xyz="0 0 +0.30" rpy="0 0 0" />
</hokuyo_utm30lx_model> -->

  <xacro:macro name="sick_lms1xx" params="frame:=laser topic:=scan sample_size:=720 update_rate:=50
               min_angle:=-2.35619 max_angle:=2.35619 min_range:=0.1 max_range:=30.0 robot_namespace:=/" >
    <link name="${frame}">
      <inertial>
        <mass value="1.1" />
        <origin xyz="0 0 0" />
        <inertia ixx="${0.0833333 * 1.1 * (0.102*0.102 + 0.152*0.152)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * 1.1 * (0.105*0.105 + 0.152*0.152)}" iyz="0.0"
          izz="${0.0833333 * 1.1 * (0.105*0.105 + 0.102*0.102)}" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!-- Origin of this mesh is the focal point of the LIDAR. -->
          <mesh filename="package://lms1xx/meshes/sick-lms1xx.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.05" rpy="0 0 0" />
        <geometry>
          <box size="0.105 0.1 0.1" />
        </geometry>
      </collision>
    </link>

    <joint name="${namespace}/base_joint_box" type="fixed">
      <origin xyz="-0.3 0 -0.12" rpy="0 0 0" />
      <parent link="${namespace}/base_link" />
      <child link="${frame}" />
    </joint>

    <gazebo reference="${frame}">
      <turnGravityOff>true</turnGravityOff>
      <sensor type="ray" name="${frame}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>${update_rate}</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>${sample_size}</samples>
              <resolution>1</resolution>
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>${min_range}</min>
            <max>${max_range}</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
          <topicName>${topic}</topicName>
          <frameName>${frame}</frameName>
          <robotNamespace>${robot_namespace}</robotNamespace>
        </plugin>
      </sensor>
    </gazebo>
</xacro:macro>

  <xacro:property name="arm_length" value="0.6" />
  <xacro:property name="mass_arm" value="0.01" />

   <link name="box">
    <xacro:box_inertial x="${arm_length}" y="0.03" z="0.01" mass="1">
      <origin xyz="${arm_length/2} 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.2 0.2 0.2"/> <!-- [m] [m] [m] -->
      </geometry>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.2 0.2 0.2"/> <!-- [m] [m] [m] -->
       </geometry>
    </collision>
  </link>


    <joint name="${namespace}/base_joint_box" type="fixed">
      <origin xyz="-0.3 0 -0.12" rpy="0 0 0" />
      <parent link="${namespace}/base_link" />
      <child link="box" />
    </joint>

</robot>
